.PHONY: clean

CC=gcc
CFLAGS=-Wall -Wextra -Werror -ansi -Wpedantic

EXE=exo1 exo2 exo3 exo4 exo5 exo6 exo7 exo8 exo9 exo10 exo12
OBJ1=exo1.o
OBJ2=exo2.o
OBJ3=exo3.o
OBJ4=exo4.o
OBJ5=exo5.o
OBJ6=exo6.o
OBJ7=exo7.o
OBJ8=exo8.o
OBJ9=exo9.o
OBJ10=exo10.o
OBJ12=exo12.o

all: $(EXE)

exo1: $(OBJ1)
exo2: $(OBJ2)
exo3: $(OBJ3)
exo4: $(OBJ4)
exo5: $(OBJ5)
exo6: $(OBJ6)
exo7: $(OBJ7)
exo8: $(OBJ8)
exo9: $(OBJ9)
exo10: $(OBJ10)
exo12: $(OBJ12)

clean:
	rm -f *.o $(EXE)
